server:
  port: 8080
  servlet:
    context-path: /studyE

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/studyE"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 462004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud_name: dz32nqnp3
  api_key: 535356454445185
  api_secret: RgLQQ17SP4en8Zcq1vxYeldQ7yI